-- This is a test file.

CREATE TABLE TABLE1 (
  NAME VARCHAR(255),
  `FIRST_NAME` VARCHAR(255),
  PROFESSION VARCHAR(50) NOT NULL,
  CONSTRAINT TABLE1_PK PRIMARY KEY (NAME, FIRST_NAME),
  FOREIGN KEY (PROFESSION) REFERENCES TABLE2 (PROFESSION)
);

CREATE TABLE TABLE2 (
  PROFESSION VARCHAR(255),
  RECOGNITION VARCHAR(255),
  [COMMENTS] TEXT,
  PRIMARY KEY (PROFESSION),
);
